version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-gcm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-senha_segura}
      POSTGRES_DB: ${DB_NAME:-gcm_db}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  web:
    build: ./api_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  pg_data:
